//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class monster
    {
        
        public uint id;
        
        public string name = "";
        
        public int hp;
        
        public int def;
        
        public float mass;
        
        public int atk;
        
        public string monster_view = "";
        
        public string monster_behaviour_tree = "";
        
        public object diy_obj;
    }
    
    public class monsters
    {
        
        private static System.Collections.Generic.Dictionary<string, monster> m_records;
        
        public static System.Collections.Generic.Dictionary<string, monster> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, monster>)Foundations.Excels.ExcelAnalyzer.init("monster");
            }
        }
        
        public static bool TryGetValue(string key, out monster record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("monster", key, out record);
        }
    }
}
